default_platform(:ios)

platform :ios do
  desc "Sync certificates and provisioning profiles"
  lane :sync_certificates do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_KEY_ISSUER_ID"],
      key_content: ENV["APPSTORE_KEY_CONTENT"],
      is_key_content_base64: true,
    )

    match(type: "appstore")
  end

  desc "Deploy to App Store"
  lane :deploy do
    keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
    keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]

    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_KEY_ISSUER_ID"],
      key_content: ENV["APPSTORE_KEY_CONTENT"],
    )

    if is_ci
      delete_keychain(
        name: keychain_name
      ) if File.exist? File.expand_path("~/Library/Keychains/#{keychain_name}-db")
      create_keychain(
        name: keychain_name,
        password: keychain_password,
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false,
        require_create: true,
      )
    end

    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Runner.xcodeproj",
      team_id: ENV["TEAM_ID"],
      bundle_identifier: "dev.flchart.app",
      profile_name: "match AppStore dev.flchart.app",
      code_sign_identity: "Apple Distribution",
    )

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "dev.flchart.app" => "match AppStore dev.flchart.app"
        }
      }
    )

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
    )
  end
end
