name: Code Verification

on: [ push, pull_request ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Print Flutter version
        run: flutter --version
      - name: Get packages
        run: flutter pub get
      - name: Check formatting
        run: make checkFormat
      - name: Analyze the source code
        run: make analyze
      - name: Run tests
        run: make test